version: '3.1'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres-15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: dzisiajpowtorzylem
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
